### ISSUE TITLE
Tabular Collection Ignore Find Arguments of Publish?

### ISSUE THREAD

**Issue by markudevelop** [Meteor-Community-Packages/meteor-tabular#13]
Hey, 
This package is awesome have started creating my own table, And I was pleasantly surprised that I can use the full datatables API it's really awesome. 

My issue I publish meteor collection this way (Server-side of course):

```
Meteor.publish('userProducts', function() {
  return userProducts.find({userId: this.userId}, {fields: {
    userId:1,
    name:1, 
    price:1, 
    status:1,
    marketPlace:1,
    updated_at:1
  }});
});
```

But it seems the find by `userId: this.userId` doesn't work because I get the full collection of all users (I'm trying to show only the current users products) the fields part works fine. Am I doing it wrong? Or this is a problem?

**Comment by mOsCpU0** [comment]
Hello, @aldeed 

I created the same thing, but how did he solve it ?, I have this problem, in the data i have (example: owner: 4bu9iDhtCDcZ7qJNr)


I applied your solution:
```
TabularTables ={};

Meteor.isClient && Template.registerHelper('TabularTables', TabularTables);

TabularTables.Dealers = new Tabular.Table({
  name: "Dealers",
  collection: Dealers,
  autoWidth: false,
  responsive: true,
  columns:[
     {data: "owner", title: "Name"},
     {data: "p_iva", title: "Phone"},
     {data: "p_iva", title: "Phone"},
     {data: "name", title: "Name"},
  ],
  allow: function (userId, selector) {
    if (selector.userId !== userId && selector.userId !== +selector.userId) {
      return false; // not allowed to access another user's products
    }
  }
```
But it does not work :(
How can I fix it? Please help me!
