### ISSUE TITLE
aldeed:tabular `3.0.0-rc.4` is not Compatible with Meteor `3.0.4`

### ISSUE THREAD

**Issue by distalx** [Meteor-Community-Packages/meteor-tabular#463]
**Describe the bug**
`aldeed:tabular` version `3.0.0-rc.4` is not functioning correctly with Meteor version `3.0.4`. The issue arises because Meteor 3.0.4 utilizes a `3.0.0` version of `blaze-html-templates`.

**To Reproduce**
1. Clone the reproduction repository.
2. Run `meteor npm install && meteor` in your terminal.
3. Open `localhost:3000` in your web browser.
4. Observe that the table does not render.

**Expected behavior**
When following the above steps, the table should render correctly, displaying the default "links" collection data.

**Additional context**
- Meteor Version: `3.0.4`
- aldeed:tabular Version: `3.0.0-rc.4`

**Reproduction Repo:** [Link to Reproduction Repository](https://github.com/distalx/ex-tabular-table-w-3-0-4)

**Comment by jankapunkt** [comment]
@distalx I checked your repo and it seems you have no datatables npm packages installed. Please see the following comment on why datatables IS NOT a hard-coded dependency anymore:

https://github.com/Meteor-Community-Packages/meteor-tabular/pull/459#issuecomment-2411308153

**Comment by distalx** [comment]
@jankapunkt, thank you for your quick response.

Installing `datatables.net` and `datatables.net-dt` for the default style, along with adding the following function call `Tabular.init();`, resolves my issue. 

I have a follow-up question: in the comment, it mentions passing the DataTables instance to the `Tabular.init()` call like this: `Tabular.init({DataTables})`. However, if I don't pass the DataTables instance, it still works.

I think the README should be updated to include the following section:

**Updating to 3.0**

- Make sure to install the DataTables packages from version 3; we are no longer hard-pinning them.
  ```bash
  meteor npm install --save datatables.net datatables.net-dt
  ```
- Ensure you initialize Tabular on your client-side code as follows:
  ```javascript
  // Client-side, ideally in `imports/startup/client/index.js`
  import Tabular from 'meteor/aldeed:tabular';
  import 'datatables.net'
  import 'datatables.net-dt/css/dataTables.dataTables.css'
  Tabular.init();
  // in case of datatables.net >= v2
  import Tabular from 'meteor/aldeed:tabular';
  import DataTables from 'datatables.net'
  import 'datatables.net-dt/css/dataTables.dataTables.css'
  Tabular.init({DataTables});
  ```

I can raise a PR to update the README.
